// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RiverBooks.Books;

#nullable disable

namespace RiverBooks.Books.Data.Migrations
{
    [DbContext(typeof(BookDbContext))]
    [Migration("20240704215952_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Books")
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RiverBooks.Books.Book", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Books", "Books");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5edbfe2c-f3f4-4b4c-9129-61c1b45e89d1"),
                            Author = "J.R.R. Tokient",
                            Price = 10.99m,
                            Title = "The followship of the Ring"
                        },
                        new
                        {
                            Id = new Guid("e03696c8-78a3-49e7-bc48-481ef94f0483"),
                            Author = "J.R.R. Tokient",
                            Price = 12.99m,
                            Title = "The followship of the Ring II"
                        },
                        new
                        {
                            Id = new Guid("90514419-d88a-40dc-91ea-67eb32107a29"),
                            Author = "J.R.R. Tokient",
                            Price = 20.99m,
                            Title = "The followship of the Ring III"
                        },
                        new
                        {
                            Id = new Guid("a9eb78d7-f5e2-47a6-860d-d42d28a7214a"),
                            Author = "J.R.R. Tokient",
                            Price = 30.99m,
                            Title = "The followship of the Ring IV"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
